[package]
authors = ["Architect Financial Technologies LLC"]
categories = ["finance", "cryptography::cryptocurrencies"]
description = "Architect.xyz Trading Platform SDK"
documentation = "https://docs.rs/architect-sdk"
edition = "2021"
homepage = "https://www.architect.xyz"
keywords = ["crypto", "hft", "trading", "finance"]
license = "AGPL-3.0-only"
name = "architect-sdk"
version = "0.5.21"

[dependencies]
anyhow = { workspace = true }
api = { package = "architect-api", version = "0.5.21", path = "../api", features = ["netidx"] }
arc-swap = { workspace = true }
arcstr = { workspace = true }
async-stream = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
derive_builder = { workspace = true }
enumflags2 = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
fxhash = { workspace = true }
immutable-chunkmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
maybe-owned = { workspace = true }
md-5 = { workspace = true }
netidx = { workspace = true }
netidx-archive = { workspace = true }
netidx-core = { workspace = true }
netidx-derive = { workspace = true }
netidx-protocols = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
openssl = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pkcs8 = { workspace = true }
portable-atomic = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
smallvec = { workspace = true }
sysinfo = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
zeroize = { workspace = true }
zstd = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
    "md-5"
]
