[package]
authors = ["Architect Financial Technologies LLC"]
description = "Architect.xyz Trading Platform SDK"
documentation = "https://docs.rs/architect-sdk"
homepage = "https://www.architect.xyz"
license = "AGPL-3.0-only"
name = "architect-sdk"
version = "0.2.0"
edition = "2021"
keywords = ["crypto", "hft", "trading", "finance"]
categories = ["finance", "cryptography::cryptocurrencies"]

[dependencies]
anyhow = { workspace = true }
api = { package = "architect-api", version = "0.2.1", path = "../api" }
arc-swap = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
fxhash = { workspace = true }
immutable-chunkmap = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
md-5 = { workspace = true }
netidx = { workspace = true }
netidx-archive = { workspace = true }
netidx-core = { workspace = true }
netidx-derive = { workspace = true }
netidx-protocols = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
openssl = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
portable-atomic = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
smallvec = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
zstd = { workspace = true }
